export const blogCard = [
  {
    label: 'Architect',
    textThin: 'Lorem ipsum dolor sit amet, consecti advipiscings',
    textBold: 'elit, sed do&nbsp;eiusmod tempor incididunt...',
    img: '/img/blog-user-1.jpg',
    bg: ['/img/blog-card-bg-1.jpg', '/img/blog-card-bg-1.avif', '/img/blog-card-bg-1.webp'],
    name: 'Carlos James',
    date: '24 December, 2022',
    datetime: '2022-12-24',
  },
  {
    label: 'Builder',
    textThin: 'Ut&nbsp;enim ad&nbsp;minim veniam, quis nosti exercitations',
    textBold: 'ullamco laboris nisi ut&nbsp;aliquip...',
    img: '/img/blog-user-2.jpg',
    bg: ['/img/blog-card-bg-2.jpg', '/img/blog-card-bg-2.avif', '/img/blog-card-bg-2.webp'],
    name: 'Jacob William',
    date: '29 December, 2022',
    datetime: '2022-12-29',
  },
  {
    label: 'Architect',
    textThin: 'Lorem ipsum dolor sit amet, consecti advipiscings',
    textBold: 'elit, sed do&nbsp;eiusmod tempor incididunt...',
    img: '/img/blog-user-3.jpg',
    bg: ['/img/blog-card-bg-3.jpg', '/img/blog-card-bg-3.avif', '/img/blog-card-bg-3.webp'],
    name: 'Marcus Johns',
    date: '24 November, 2022',
    datetime: '2022-11-24',
  },
  {
    label: 'Builder',
    textThin: 'Ut&nbsp;enim ad&nbsp;minim veniam, quis nosti exercitations',
    textBold: 'elit, sed do&nbsp;eiusmod tempor incididunt...',
    img: '/img/blog-user-4.jpg',
    bg: ['/img/blog-card-bg-4.jpg', '/img/blog-card-bg-4.avif', '/img/blog-card-bg-4.webp'],
    name: 'Kane Cutting',
    date: '15 Jule, 2020',
    datetime: '2020-07-15',
  },
];
