import { accordeon } from './modules/accordeon';
import { createCard } from './modules/projects-card';
import { blogCards } from './modules/blogCards';
import { scrollTopButton } from './modules/scrollTopButton';
import { slider } from './modules/slider';
import { submitForm } from './modules/submitForm';
import { trailers } from './modules/trailers';
import { mobileMenu } from './modules/mobileMenu';
import { headerBackgroundColor } from './modules/headerBackgroundColor';
// import { cb } from './modules/criticalStyle';

accordeon();
createCard();
slider();
trailers();
scrollTopButton();
submitForm();
blogCards();
mobileMenu();
headerBackgroundColor();
// cb();
